#ifndef PROTOCOL_IDS_HPP_
#define PROTOCOL_IDS_HPP_

#include <cstdint>

enum PacketFunction : uint8_t {
	PACKET_FUNC_SYS = 0,
	PACKET_FUNC_LED,
	PACKET_FUNC_BUZZER,
	PACKET_FUNC_MOTOR,
	PACKET_FUNC_PWM_SERVO,
	PACKET_FUNC_BUS_SERVO,
	PACKET_FUNC_KEY,
	PACKET_FUNC_IMU,
	PACKET_FUNC_GAMEPAD,
	PACKET_FUNC_SBUS,
	PACKET_FUNC_CHASSIS_CTRL, 
	PACKET_FUNC_CHASSIS_FEEDBACK, 
	PACKET_FUNC_NONE,
};

#endif /* PROTOCOL_IDS_HPP_ */
